version: "3.8"

services:
  tsi-document-share:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://194.195.92.47:5000
      - NEXT_PUBLIC_API_URL=http://194.195.92.47:5000
      - DATABASE_URL=mysql://root:admin@194.195.92.47:3309/document-share-tsi
      - AUTH_SECRET=X8NLXgHyjhL7S3mqxvQgwfBsqT+6PBQnvxd4f9ci7WE=
      - NEXT_PUBLIC_S3_ENDPOINT=https://is3.cloudhost.id
      - NEXT_PUBLIC_S3_REGION=auto
      - NEXT_PUBLIC_S3_BUCKET_NAME=document-share
      - NEXT_PUBLIC_S3_COMPANY=tsi
      - S3_ACCESS_KEY_ID=UW62PY9WMIW94GSEODT0
      - S3_SECRET_ACCESS_KEY=G1YfF7OoccmFc33UV70ZVB0w6uROplNKBPlDg4oh
    volumes:
      - ./logs:/app/logs
